#!/usr/bin/env bash

echo '## Creating a new branch! ##'

while getopts n:b: flag
do
    case "${flag}" in
        n) number=${OPTARG};;
        b) branch_name=${OPTARG};;
    esac
done

if [ -z $number ] || [ -z $branch_name ]; then
  echo "Need jira number (-n)"
  echo "Branch name (-b) "
  exit 1
fi

echo $number;
echo $branch_name;

#To crete a banch on a worktree
#and setup the env to be ready to code
#
echo $1
echo $2

mkdir -p -- "$1" &&
cd -P -- "$1"
touch foo

echo $1

exec bash

git worktree add -b "fix_BG-$number\__$branch_name" "b-$branch_name"

cd "b-${branch_name}"

cp .env.sample .env

ln -n ../.rgignore .

nvm use

yarn

echo End!;
