#!/usr/bin/env bash

export GOPATH=$HOME/go
export DOTNET_ROOT=$HOME/dotnet
export ASPNETCORE_ENVIRONMENT=Development

addToPath $HOME/dotnet
addToPathFront $HOME/.local/scripts
addToPathFront $HOME/.cargo/env
addToPathFront $GOPATH/bin
addToPathFront /opt/homebrew/opt/ruby/bin
#export PATH="$PATH:/opt/yarn-[version]/bin"
